language: clojure
lein: lein2
script: lein2 midje
after_script: lein2 uberjar
services:
  - redis-server
deploy:
  provider: releases
  api_key:
    secure: HQPt93elgCvUiLPz4xNwuNKvBcg+Li+1CVgTRweuKAnv4/3Ly+DiCGI3ZmBDSoP6NXNRC8GzpqUnPXQzMn0qexrRDHzuoV4aSLbN8b7QNTRxg2/AxnLUS+UywMGr+SUnteHx50Pyqy24nEUG1bPCW9XdnmiBX41y2hwip9ejdQ4=
  file: target/fastchat-2.0.0-standalone.jar
  on:
    repo: diogok/FastChat
